# Generated by Django 5.0.6 on 2024-12-23 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0004_contestapplication'),
        ('member', '0012_regularmember_staffmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='contests', to='member.organizationbranch'),
        ),
    ]
