# Generated by Django 5.0.6 on 2024-12-23 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0005_contest_branch'),
        ('member', '0012_regularmember_staffmember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contests', to='member.organizationbranch'),
        ),
    ]
