# Generated by Django 5.0.6 on 2024-12-23 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0006_alter_contest_branch'),
        ('work', '0002_remove_work_likes_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='winner',
            field=models.ForeignKey(blank=True, help_text='Winning work of the contest', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='winning_contests', to='work.work'),
        ),
    ]
