# Generated by Django 5.1.3 on 2025-01-02 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0008_remove_contest_branch'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contest',
            options={'ordering': ['-created_at']},
        ),
    ]
