# Generated by Django 5.0.6 on 2025-01-06 23:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0009_alter_contest_options'),
        ('member', '0016_alter_organization_options_alter_member_address_and_more'),
        ('work', '0005_alter_category_options_alter_image_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Contest', 'verbose_name_plural': 'Contests'},
        ),
        migrations.AlterModelOptions(
            name='contestapplication',
            options={'verbose_name': 'Application', 'verbose_name_plural': 'Applications'},
        ),
        migrations.AlterField(
            model_name='contest',
            name='award_condition',
            field=models.CharField(choices=[('likes', 'No. of likes'), ('admin', 'To be decided by admin')], default='admin', help_text='Condition for awarding the contest winner', max_length=10, verbose_name='condition'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='eligibility_criteria',
            field=models.TextField(blank=True, help_text='Eligibility criteria for participants', verbose_name='eligible criteria'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='end_date',
            field=models.DateTimeField(verbose_name='end date'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='explanation',
            field=models.TextField(verbose_name='explanation'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='is_private',
            field=models.BooleanField(default=False, help_text='Private contest (visible only to organization members)', verbose_name='is private'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contests', to='member.organization', verbose_name='organization'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='start_date',
            field=models.DateTimeField(verbose_name='start date'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/', verbose_name='thumbnail'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='winner',
            field=models.ForeignKey(blank=True, help_text='Winning work of the contest', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='winning_contests', to='work.work', verbose_name='winner'),
        ),
        migrations.AlterField(
            model_name='contestapplication',
            name='contest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='contest.contest', verbose_name='contest'),
        ),
        migrations.AlterField(
            model_name='contestapplication',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='contestapplication',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL, verbose_name='member'),
        ),
        migrations.AlterField(
            model_name='contestapplication',
            name='submission_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='submission date'),
        ),
        migrations.AlterField(
            model_name='contestapplication',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='work.work', verbose_name='work'),
        ),
    ]
