# Generated by Django 5.0.6 on 2024-10-15 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.RemoveField(
            model_name='member',
            name='invited_organizations',
        ),
        migrations.RemoveField(
            model_name='member',
            name='join_requests',
        ),
        migrations.AlterField(
            model_name='member',
            name='admin_role',
            field=models.CharField(choices=[('company_admin', 'Company Administrator'), ('branch_admin', 'Branch Administrator'), ('system_admin', 'System Administrator'), ('protector', 'Protector'), ('child', 'Child')], default='system_admin', help_text='Role of the member in the organization', max_length=50),
        ),
        migrations.AlterField(
            model_name='member',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='member',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
