# Generated by Django 5.0.6 on 2024-10-15 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_alter_member_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='admin_role',
        ),
        migrations.RemoveField(
            model_name='member',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='member',
            name='member_type',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='email',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='phone',
        ),
        migrations.AddField(
            model_name='member',
            name='role',
            field=models.CharField(choices=[('company_admin', 'Company Administrator'), ('branch_admin', 'Branch Administrator'), ('system_admin', 'System Administrator'), ('group_member', 'Group Member'), ('protector', 'Protector'), ('child', 'Child')], default='protector', help_text='Role of the member in the organization', max_length=50),
        ),
        migrations.AlterField(
            model_name='organization',
            name='organization_type',
            field=models.CharField(choices=[('school', 'School'), ('company', 'Company'), ('museum', 'Museum'), ('other', 'Other')], default='other', help_text='Type of organization', max_length=50),
        ),
    ]
