# Generated by Django 5.0.6 on 2024-12-22 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0009_alter_member_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='member.organization'),
        ),
        migrations.CreateModel(
            name='OrganizationBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Branch name', max_length=255)),
                ('email', models.EmailField(help_text='Branch admin email', max_length=254)),
                ('staff_name', models.CharField(help_text='Branch admin staff name', max_length=255)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='member.organization')),
            ],
        ),
    ]
