# Generated by Django 5.0.6 on 2024-12-22 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0010_member_organization_organizationbranch'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='email',
            field=models.EmailField(default='org@museume.com', help_text='Organization admin email', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='staff_name',
            field=models.CharField(default='staff', help_text='Organization admin staff name', max_length=255),
            preserve_default=False,
        ),
    ]
