# Generated by Django 5.0.6 on 2024-12-27 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0008_remove_contest_branch'),
        ('member', '0013_member_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='branch',
        ),
        migrations.DeleteModel(
            name='OrganizationBranch',
        ),
    ]
