# Generated by Django 5.0.6 on 2025-01-06 23:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0015_organization_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'verbose_name': 'Organization', 'verbose_name_plural': 'Organizations'},
        ),
        migrations.AlterField(
            model_name='member',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='member',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='data of birth'),
        ),
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='member',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Is the member published?', verbose_name='is published'),
        ),
        migrations.AlterField(
            model_name='member',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='member.organization', verbose_name='Organization'),
        ),
        migrations.AlterField(
            model_name='member',
            name='organizations',
            field=models.ManyToManyField(blank=True, related_name='members', to='member.organization', verbose_name='Organization'),
        ),
        migrations.AlterField(
            model_name='member',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to=settings.AUTH_USER_MODEL, verbose_name='Parent Account'),
        ),
        migrations.AlterField(
            model_name='member',
            name='role',
            field=models.CharField(choices=[('company_admin', 'Company Administrator'), ('branch_admin', 'Branch Administrator'), ('system_admin', 'System Administrator'), ('group_member', 'Group Member'), ('protector', 'Protector'), ('child', 'Child')], default='protector', help_text='Role of the member in the organization', max_length=50, verbose_name='role'),
        ),
        migrations.AlterField(
            model_name='member',
            name='shared_users',
            field=models.ManyToManyField(blank=True, related_name='shared_members', to=settings.AUTH_USER_MODEL, verbose_name='shared users'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='email',
            field=models.EmailField(help_text='Organization admin email', max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='organization_icon',
            field=models.ImageField(blank=True, help_text='Profile picture of the organization', null=True, upload_to='profile_pictures/', verbose_name='icon'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='organization_type',
            field=models.CharField(choices=[('school', 'School'), ('company', 'Company'), ('museum', 'Museum'), ('other', 'Other')], default='other', help_text='Type of organization', max_length=50, verbose_name='organization type'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='member.organization', verbose_name='Parent Organization'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='staff_name',
            field=models.CharField(help_text='Organization admin staff name', max_length=255, verbose_name='staff name'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
    ]
