# Generated by Django 5.0.6 on 2025-01-15 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0016_alter_organization_options_alter_member_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='organization_type',
        ),
        migrations.AddField(
            model_name='member',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='is approved'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_code',
            field=models.CharField(blank=True, max_length=6, verbose_name='Organization Code'),
        ),
    ]
