# Generated by Django 5.1.3 on 2024-11-18 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('tag', models.CharField(max_length=255)),
                ('is_free', models.BooleanField(default=False)),
                ('class_type', models.CharField(choices=[('real_time', 'Real Time'), ('recorded', 'Recorded')], default='recorded', max_length=20)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='artist_class_thumbnails/')),
                ('youtube_url', models.URLField(blank=True, null=True)),
                ('zoom_url', models.URLField(blank=True, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
