# Generated by Django 5.1.3 on 2024-11-19 11:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist_class', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberClassSignup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signed_up_at', models.DateTimeField(auto_now_add=True)),
                ('artist_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signups', to='artist_class.artistclass')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_signups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('member', 'artist_class')},
            },
        ),
    ]
