# Generated by Django 5.1.3 on 2024-11-28 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artist_class', '0002_memberclasssignup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artistclass',
            old_name='youtube_url',
            new_name='url',
        ),
        migrations.RemoveField(
            model_name='artistclass',
            name='zoom_url',
        ),
    ]
