# Generated by Django 5.1.3 on 2024-11-28 14:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist_class', '0003_rename_youtube_url_artistclass_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='memberclasssignup',
            name='attended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='memberclasssignup',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='memberclasssignup',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='memberclasssignup',
            index=models.Index(fields=['member'], name='artist_clas_member__085126_idx'),
        ),
        migrations.AddIndex(
            model_name='memberclasssignup',
            index=models.Index(fields=['artist_class'], name='artist_clas_artist__5b1288_idx'),
        ),
    ]
