# Generated by Django 5.1.3 on 2025-01-02 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artist_class', '0006_artistclass_cost_payment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artistclass',
            options={'ordering': ['-created_at']},
        ),
    ]
