# Generated by Django 5.0.6 on 2025-01-06 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist_class', '0007_alter_artistclass_options'),
        ('work', '0005_alter_category_options_alter_image_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artistclass',
            options={'ordering': ['-created_at'], 'verbose_name': 'Artist Class', 'verbose_name_plural': 'Artist Classes'},
        ),
        migrations.AlterField(
            model_name='artistclass',
            name='category',
            field=models.CharField(max_length=255, verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='artistclass',
            name='class_type',
            field=models.CharField(choices=[('real_time', 'Real Time'), ('recorded', 'Recorded')], default='recorded', max_length=20, verbose_name='class type'),
        ),
        migrations.AlterField(
            model_name='artistclass',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='cost'),
        ),
        migrations.AlterField(
            model_name='artistclass',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='artistclass',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='end date'),
        ),
        migrations.AlterField(
            model_name='artistclass',
            name='is_free',
            field=models.BooleanField(default=False, verbose_name='is free'),
        ),
        migrations.AlterField(
            model_name='artistclass',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='artistclass',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='start date'),
        ),
        migrations.AlterField(
            model_name='artistclass',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='artist_classes', to='work.tag', verbose_name='tags'),
        ),
        migrations.AlterField(
            model_name='artistclass',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='artist_class_thumbnails/', verbose_name='thumbnail'),
        ),
        migrations.AlterField(
            model_name='artistclass',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='artistclass',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='url'),
        ),
    ]
