# Generated by Django 5.0.6 on 2025-01-06 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_site', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publicnavbar',
            options={'verbose_name': 'Public NavBar', 'verbose_name_plural': 'Public NavBar'},
        ),
        migrations.AlterField(
            model_name='publicnavbar',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='publicnavbar',
            name='navbar_type',
            field=models.CharField(choices=[('blog', 'Blog'), ('about', 'About Us')], default='blog', help_text='Type of navbar', max_length=10, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='publicnavbar',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='publicnavbar',
            name='url',
            field=models.CharField(max_length=100, verbose_name='url'),
        ),
    ]
