# Generated by Django 5.0.6 on 2024-12-24 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0002_remove_work_likes_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
