# Generated by Django 5.1.3 on 2025-01-02 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='add_type',
            field=models.CharField(choices=[('banner', 'Banner'), ('logo', 'Logo')], default='banner', help_text='Type of the image', max_length=10),
        ),
    ]
