# Generated by Django 5.0.6 on 2025-01-06 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0002_advertisement_add_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisement',
            options={'verbose_name': 'Advertisement', 'verbose_name_plural': 'Advertisements'},
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='add_type',
            field=models.CharField(choices=[('banner', 'Banner'), ('logo', 'Logo')], default='banner', help_text='Type of the image', max_length=10, verbose_name='ad type'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='banner_frame',
            field=models.CharField(choices=[('fixed', 'Fixed')], default='fixed', help_text='Banner frame type', max_length=50, verbose_name='banner frame'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='banner_image',
            field=models.ImageField(help_text='Upload the banner image', upload_to='advertisements/', verbose_name='banner image'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='end_date',
            field=models.DateTimeField(help_text='End date of the display period', verbose_name='end date'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='name',
            field=models.CharField(help_text='Name of the advertisement plan', max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='start_date',
            field=models.DateTimeField(help_text='Start date of the display period', verbose_name='start date'),
        ),
    ]
