# Generated by Django 5.0.6 on 2024-11-18 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_plan_credits_subscription_plan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='user',
            new_name='member',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='credits',
        ),
    ]
